### ISSUE TITLE
the sign in button WONT  WORK!!!

### ISSUE THREAD

**Issue by NINJACLUBREAL** [MohdYahyaMahmodi/pulsar-os#3]
i click sign in it wont wont :(

**Comment by MohdYahyaMahmodi** [comment]
It is not meant to do anything yet, the main page has not yet been finished.

**Comment by NINJACLUBREAL** [comment]
i know i went to /os.html and it dident look done :)

**Comment by MohdYahyaMahmodi** [comment]
> i know i went to /os.html and it dident look done :)

That's why the sign in does not take the user to the os.html :)
